import React from "react";
import Footer from "./Footer";
import NavBar from "./NavBar";
import Head from "next/head";
import Aos from "aos";

//Hooks
import { useEffect } from "react";

//CSS
import styles from "../styles/Layout.module.css";

const Layout = ({ children }) => {
  useEffect(() => {
    Aos.init({ duration: 1300 });
  }, []);
  return (
    <>
      <Head>
        <title>Poke Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/pokefavicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, user-scalable=no"
        ></meta>
      </Head>
      <div className={styles.main_container}>
        <NavBar />
        <main className={styles.main}>{children}</main>
        <Footer />
      </div>
    </>
  );
};

export default Layout;
